// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_QO7qcq-fbzB03-xTIWEYug-T1fKt4Oo',
    appId: '1:815190900567:web:9d9dec1ae8e9a8afe70812',
    messagingSenderId: '815190900567',
    projectId: 'wedding-5a0c0',
    authDomain: 'wedding-5a0c0.firebaseapp.com',
    storageBucket: 'wedding-5a0c0.firebasestorage.app',
    measurementId: 'G-WYMX28MZ9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhSwUKiiPRBHjaXe1zS0-T0eVQ-49Y9o0',
    appId: '1:815190900567:android:179e0146aa3215d3e70812',
    messagingSenderId: '815190900567',
    projectId: 'wedding-5a0c0',
    storageBucket: 'wedding-5a0c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAtqYMGrdE3qdL7ZTSf6BpAAt9peZF7W8',
    appId: '1:815190900567:ios:d0feb98bda740e25e70812',
    messagingSenderId: '815190900567',
    projectId: 'wedding-5a0c0',
    storageBucket: 'wedding-5a0c0.firebasestorage.app',
    iosBundleId: 'com.wedding.appBillingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAtqYMGrdE3qdL7ZTSf6BpAAt9peZF7W8',
    appId: '1:815190900567:ios:d0feb98bda740e25e70812',
    messagingSenderId: '815190900567',
    projectId: 'wedding-5a0c0',
    storageBucket: 'wedding-5a0c0.firebasestorage.app',
    iosBundleId: 'com.wedding.appBillingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_QO7qcq-fbzB03-xTIWEYug-T1fKt4Oo',
    appId: '1:815190900567:web:7b5e37694fef5232e70812',
    messagingSenderId: '815190900567',
    projectId: 'wedding-5a0c0',
    authDomain: 'wedding-5a0c0.firebaseapp.com',
    storageBucket: 'wedding-5a0c0.firebasestorage.app',
    measurementId: 'G-87P6LLVTZZ',
  );
}
