// ============================================================
// utils/app_strings.dart  →  lib/utils/app_strings.dart (NEW FILE)
// Tamil & English language strings
// Usage: AppStrings.t('key') — returns current language string
// ============================================================

import 'package:get/get.dart';

class AppStrings {
  static final _lang = 'en'.obs;

  static String get currentLang => _lang.value;
  static bool get isTamil => _lang.value == 'ta';

  static void setEnglish() => _lang.value = 'en';
  static void setTamil()   => _lang.value = 'ta';
  static void toggle() =>
      _lang.value = _lang.value == 'en' ? 'ta' : 'en';

  static String t(String key) {
    final map = _lang.value == 'ta' ? _tamil : _english;
    return map[key] ?? key;
  }

  static const _english = {
    'appbar_title'      : 'MOHAMED YOUSUF & HAJIMA BEE',
    'bismillah'         : 'In the name of Allah, the Most Gracious, the Most Merciful',
    'story_label'       : 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ',
    'story_title'       : 'Our Story',
    'story_text'        : 'What Allah has written, no pen can erase. Their story was penned in the heavens long before they ever met. Through every prayer, every patient moment, and every act of faith — they were being guided toward each other. Today, with gratitude in their hearts and joy in their souls, they step into this sacred bond of Nikkah together. Alhamdulillah for this beautiful blessing.',
    'dua_label'         : 'Nikkah Du\'a',
    'dua_title'         : 'Blessed Union',
    'dua_arabic'        : 'بَارَكَ اللهُ لَكَ وَبَارَكَ عَلَيْكَ وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ',
    'dua_transliteration': 'Bārakallāhu laka wa bāraka \'alaika\nwa jama\'a bainakumā fī khair',
    'dua_meaning'       : '"May Allah bless you, and shower His blessings upon you, and join you together in goodness."',
    'couple_label'      : 'The Couple',
    'couple_title'      : 'Groom & Bride',
    'groom_name'        : 'Mohamed Yousuf',
    'groom_role'        : 'The Groom',
    'groom_bio'         : 'A man of faith, strength, and warmth. He walks with humility and leads with love, ready to build a blessed home together.',
    'bride_name'        : 'Hajima Bee',
    'bride_role'        : 'The Bride',
    'bride_bio'         : 'A woman of grace, gentleness, and light. Her smile brightens every room and her heart is full of kindness and beautiful dreams.',
    'parents_label'     : 'With Blessings Of',
    'parents_title'     : 'Our Families',
    'bride_parents'     : 'Bride\'s Parents',
    'bride_father'      : 'Ikram Basha',
    'bride_mother'      : 'Maimun Bee',
    'groom_parents'     : 'Groom\'s Parents',
    'groom_father'      : 'Basheer',
    'groom_mother'      : 'Jibitha Begam',
    'son_of'            : 'Son of',
    'daughter_of'       : 'Daughter of',
    'and'               : '&',
    'event_label'       : 'Join Us',
    'event_title'       : 'Event Details',
    'nikkah_title'      : 'NIKKAH CEREMONY',
    'nikkah_date'       : 'July 05, 2026  ·  10:30 AM – 12:00 PM',
    'nikkah_hijri'      : '19 Muharram 1448 AH',
    'nikkah_venue'      : 'G.R.P Lakshmi Mahal,\nE.C.R Main Road, Anumandai (Old Tollgate)',
    'nikkah_dress'      : 'Traditional & Formal Attire',
    'location_label'    : 'Find Us',
    'location_title'    : 'Venue',
    'tap_directions'    : 'Tap for directions',
    'get_directions'    : 'GET DIRECTIONS',
    'rsvp_label'        : 'Kindly Reply By June 25, 2026',
    'rsvp_title'        : 'RSVP',
    'rsvp_name_label'   : 'YOUR NAME',
    'rsvp_name_hint'    : 'Enter your full name',
    'rsvp_phone_label'  : 'PHONE NUMBER',
    'rsvp_phone_hint'   : 'Your contact number',
    'rsvp_attend_q'     : 'WILL YOU ATTEND?',
    'rsvp_accept'       : 'Joyfully Accept',
    'rsvp_decline'      : 'Regretfully Decline',
    'rsvp_submit'       : 'Send My Response  ✦',
    'rsvp_success_title': 'We\'re overjoyed!',
    'rsvp_success_msg'  : 'Thank you! We can\'t wait to celebrate with you. See you at the venue! 🥂',
    'rsvp_decline_title': 'You will be missed',
    'rsvp_decline_msg'  : 'Thank you for letting us know. Your love and blessings mean the world to us. 💕',
    'rsvp_back'         : 'Back to Invitation',
    'rsvp_err_name'     : 'Please enter your name',
    'rsvp_err_phone'    : 'Please enter your phone number',
    'rsvp_err_attend'   : 'Please select your attendance',
    'share_label'       : 'SHARE THE JOY',
    'share_whatsapp'    : 'WhatsApp',
    'share_btn'         : 'Share',
    'tl_nikkah'         : 'Nikkah', 'tl_nikkah_lbl': 'Sacred bond',
    'tl_walima'         : 'Walima', 'tl_walima_lbl': 'Celebration',
    'tl_dua'            : 'Du\'a',  'tl_dua_lbl'   : 'Blessings',
    'tl_home'           : 'Home',   'tl_home_lbl'  : 'New life',
    'tl_always'         : 'Always', 'tl_always_lbl': 'Together',
  };

  static const _tamil = {
    'appbar_title'      : 'மொஹமட் யூசுஃப் & ஹஜிமா பீ',
    'bismillah'         : 'அன்புமிக்க, கருணைமிக்க அல்லாஹ்வின் பெயரால்',
    'story_label'       : 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ',
    'story_title'       : 'எங்கள் கதை',
    'story_text'        : 'அல்லாஹ் எழுதியதை எந்த பேனாவும் அழிக்க முடியாது. அவர்கள் சந்திப்பதற்கு முன்பே அவர்களின் கதை வானில் எழுதப்பட்டிருந்தது. ஒவ்வொரு துஆவிலும், ஒவ்வொரு பொறுமையான தருணத்திலும் — அவர்கள் ஒருவருக்கொருவர் வழிகாட்டப்பட்டனர். இன்று, இதயங்களில் நன்றியுடனும் ஆன்மாக்களில் மகிழ்ச்சியுடனும், அவர்கள் இந்த புனிதமான நிக்காஹ் உறவில் ஒன்றாக அடியெடுத்து வைக்கிறார்கள். அல்ஹம்துலில்லாஹ்.',
    'dua_label'         : 'நிக்காஹ் துஆ',
    'dua_title'         : 'ஆசீர்வாதமான இணைவு',
    'dua_arabic'        : 'بَارَكَ اللهُ لَكَ وَبَارَكَ عَلَيْكَ وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ',
    'dua_transliteration': 'பாரகல்லாஹு லக வபாரக அலைக\nவஜமஃ பைனகுமா ஃபீ கைர்',
    'dua_meaning'       : '"அல்லாஹ் உங்களுக்கு அருள் புரியட்டும், உங்கள் மீது பரகத்தை வழங்கட்டும், உங்கள் இருவரையும் நன்மையில் இணைக்கட்டும்."',
    'couple_label'      : 'தம்பதியினர்',
    'couple_title'      : 'மணமகன் & மணமகள்',
    'groom_name'        : 'மொஹமட் யூசுஃப்',
    'groom_role'        : 'மணமகன்',
    'groom_bio'         : 'நம்பிக்கை, வலிமை மற்றும் அன்பின் மனிதன். அவர் பணிவுடன் நடந்து அன்புடன் வழிநடத்துகிறார்.',
    'bride_name'        : 'ஹஜிமா பீ',
    'bride_role'        : 'மணமகள்',
    'bride_bio'         : 'அருள், மென்மை மற்றும் ஒளியின் பெண். அவளது புன்னகை ஒவ்வொரு அறையையும் பிரகாசிக்கிறது.',
    'parents_label'     : 'குடும்பத்தினரின் ஆசீர்வாதத்துடன்',
    'parents_title'     : 'எங்கள் குடும்பங்கள்',
    'bride_parents'     : 'மணமகளின் பெற்றோர்',
    'bride_father'      : 'இக்ராம் பாஷா',
    'bride_mother'      : 'மைமூன் பீ',
    'groom_parents'     : 'மணமகனின் பெற்றோர்',
    'groom_father'      : 'பஷீர்',
    'groom_mother'      : 'ஜிபிதா பேகம்',
    'son_of'            : 'மகன்',
    'daughter_of'       : 'மகள்',
    'and'               : '&',
    'event_label'       : 'எங்களுடன் சேருங்கள்',
    'event_title'       : 'நிகழ்வு விவரங்கள்',
    'nikkah_title'      : 'நிக்காஹ் விழா',
    'nikkah_date'       : 'ஜூலை 05, 2026  ·  காலை 10:30 – 12:00',
    'nikkah_hijri'      : 'முஹர்ரம் 19, ஹிஜ்ரி 1448',
    'nikkah_venue'      : 'ஜி.ஆர்.பி லட்சுமி மகால்,\nஈ.சி.ஆர் மெயின் ரோட், அணுமண்டை (பழைய டோல்கேட்)',
    'nikkah_dress'      : 'பாரம்பரிய & முறையான உடை',
    'location_label'    : 'எங்கே நடக்கிறது',
    'location_title'    : 'நடைபெறும் இடம்',
    'tap_directions'    : 'வழிகாட்டுதலுக்கு தட்டவும்',
    'get_directions'    : 'வழிகாட்டுதல் பெறுக',
    'rsvp_label'        : 'ஜூன் 25, 2026 க்குள் பதிலளிக்கவும்',
    'rsvp_title'        : 'வருகை உறுதி',
    'rsvp_name_label'   : 'உங்கள் பெயர்',
    'rsvp_name_hint'    : 'உங்கள் முழு பெயரை உள்ளிடவும்',
    'rsvp_phone_label'  : 'தொலைபேசி எண்',
    'rsvp_phone_hint'   : 'உங்கள் தொடர்பு எண்',
    'rsvp_attend_q'     : 'நீங்கள் வருவீர்களா?',
    'rsvp_accept'       : 'மகிழ்ச்சியுடன் ஏற்கிறேன்',
    'rsvp_decline'      : 'வருந்தத்தக்க விதத்தில் மறுக்கிறேன்',
    'rsvp_submit'       : 'என் பதிலை அனுப்புக  ✦',
    'rsvp_success_title': 'நாங்கள் மிகவும் மகிழ்ச்சியடைகிறோம்!',
    'rsvp_success_msg'  : 'நன்றி! உங்களுடன் கொண்டாட ஆவலாக காத்திருக்கிறோம். விழா இடத்தில் சந்திப்போம்! 🥂',
    'rsvp_decline_title': 'நீங்கள் இல்லாமல் குறை உணர்வோம்',
    'rsvp_decline_msg'  : 'தெரிவித்தமைக்கு நன்றி. உங்கள் அன்பும் ஆசீர்வாதமும் எங்களுக்கு மிகவும் அர்த்தமுள்ளது. 💕',
    'rsvp_back'         : 'அழைப்பிதழுக்கு திரும்பு',
    'rsvp_err_name'     : 'உங்கள் பெயரை உள்ளிடவும்',
    'rsvp_err_phone'    : 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
    'rsvp_err_attend'   : 'உங்கள் வருகையை தேர்வு செய்யவும்',
    'share_label'       : 'மகிழ்ச்சியை பகிருங்கள்',
    'share_whatsapp'    : 'வாட்ஸ்அப்',
    'share_btn'         : 'பகிர்',
    'tl_nikkah'         : 'நிக்காஹ்', 'tl_nikkah_lbl': 'புனித பந்தம்',
    'tl_walima'         : 'வலீமா',    'tl_walima_lbl': 'கொண்டாட்டம்',
    'tl_dua'            : 'துஆ',      'tl_dua_lbl'   : 'ஆசீர்வாதம்',
    'tl_home'           : 'வீடு',     'tl_home_lbl'  : 'புதிய வாழ்க்கை',
    'tl_always'         : 'எப்போதும்','tl_always_lbl': 'ஒன்றாக',
  };
}